version: "{branch} {build}"

environment:
  matrix:
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: 3.5
      PYTHON_ARCH: 64
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 64
    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 64

init:
  - echo %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

  # Needed for builds on branches instead of PRs
  - set REPO=%CD%
  - cd .. && ren %REPO% styleguide

  - cd styleguide\wpiformat
  - py -3 setup.py build
  - py -3 setup.py install --optimize=1 --skip-build

build: false

test_script:
  - py -3 setup.py test
  - cd .. && py -3 -m wpiformat -v
  - cd wpiformat

  # One file
  - py -3 -m wpiformat -f wpiformat\__init__.py -v

  # Absolute path to file
  - py -3 -m wpiformat -f C:\projects\styleguide\wpiformat\wpiformat\__init__.py -v

  # Multiple files
  - py -3 -m wpiformat -f wpiformat\__init__.py wpiformat\__main__.py -v

  # Directory
  - py -3 -m wpiformat -f wpiformat -v

  - git --no-pager diff --exit-code HEAD  # Ensure formatter made no changes

matrix:
  fast_finish: true
